AWSTemplateFormatVersion: "2010-09-09"

Parameters:
  KeyName:
    Type: AWS::EC2::KeyPair::KeyName

Resources:
  MyInstance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t3.micro
      KeyName: !Ref KeyName
      ImageId: ami-02b297871a94f4b42

Outputs:
  InstanceId:
    Value: !Ref MyInstance
